### ISSUE TITLE
Static loggers should not be used in library code

### ISSUE THREAD

**Issue by eis** [esuomi/Daniel#1]
See longer explanation: http://wiki.apache.org/commons/Logging/StaticLog

In short, in an environment that shares its libraries runtime with multiple applications, using static logger instances break the behaviour. For applications static loggers are fine, but not for libraries.

**Comment by esuomi** [comment]
Ah, I guess it shows I don't normally work with containers...

I'll get this fixed over the weekend, for now this was just a code dump to get the most critical part out. Thank you for reporting!
